# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0574e4c7dc417faf32d16dabf139631b1eb06fabb69873fbb7d7c112d3ef8c38cd8b133acca07069daf0917410d8c4aa39778030da47df79e886481364ca4d67

test:
  secret_key_base: 7e2c5afb797212329048c0ac5f782ae796be13ec35c8f6c75fef940bcfc281a455cafa044250bac7e7af3290306dd7bc3989e6b72c23d4fc7f8ccc6b9a57257e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
